### ISSUE TITLE
Fix ENS tests not to connect to the real services that were failing on release/0.177.x

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-go#5085] opened 2024-04-24 13:08 UTC
The tests `services/ens/api_test.go` should be converted to use mocks

Disabled here: https://github.com/status-im/status-go/pull/5081

**Comment by iurimatias** [comment] 2024-05-27 13:44
@stefandunca was this done?

**Comment by stefandunca** [comment] 2024-05-27 13:57
> @stefandunca was this done?

No, the tests are still skipped.

**Comment by igor-sirotin** [comment] 2024-08-07 21:00
Duplicate of https://github.com/status-im/status-go/issues/5087

**Closed as completed by igor-sirotin** 2024-08-07 21:00 UTC
Labels: flaky test, wallet-team
