### ISSUE TITLE
MultiAccountStoreDerived should return an error when account already stored

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1896] opened 2020-03-09 09:13 UTC
# Problem

When we're trying to store existing account with `MultiAccountStoreAccount` it returns an error, `MultiAccountStoreDerived` should work the same and returns an error, currently, it rewrites account with the new password

**Comment by flexsurfer** [comment] 2020-03-09 09:13
its a v1.1 blocker

**Comment by rasom** [comment] 2020-03-09 13:56
So the problem is that we store a derived account to the same file regardless under which multiaccount it was created. The solution is either to store all derived accounts in some multiaccount specific directory (this will require migrations for existing accounts) or only to store accounts which are created through wallet's "import account" that way (this will not require migration as we hadn't released it yet but then different accounts which are created under the same multiaccount will be store in different directories).

**Comment by churik** [comment] 2020-03-10 11:52
@adambabik do you have a time to look into it?

**Comment by adambabik** [comment] 2020-03-10 12:41
@churik assigned to me, will do it today.

**Comment by gravityblast** [comment] 2020-03-10 13:36
hey @adambabik , I already found the error, I can start opening a PR with the fix

**Comment by gravityblast** [comment] 2020-03-10 13:42
@adambabik  it will be in our `go-ethereum` repo,  but then probably there will be something to fix in `status-go` tests.

**Comment by gravityblast** [comment] 2020-03-10 14:09
@adambabik https://github.com/status-im/go-ethereum/pull/87

**Comment by adambabik** [comment] 2020-03-10 14:13
@gravityblast awesome! Left one comment.

**Comment by flexsurfer** [comment] 2020-03-11 14:41
@gravityblast how can we use this change in status-react? do we need to use a new version of status-go ?

**Comment by gravityblast** [comment] 2020-03-11 16:34
it needs to be imported in `status-go`, @adambabik are you going to work on that?

**Comment by adambabik** [comment] 2020-03-11 21:01
@flexsurfer you can use https://github.com/status-im/status-go/pull/1898.

**Closed as completed** 2020-03-12 12:05 UTC
