### ISSUE TITLE
Unit tests take a lot of time on CI

### ISSUE THREAD

**Issue by yakimant** [status-im/status-go#3918] opened 2023-08-18 12:45 UTC
# Problem

Unit tests take unpredicteble and sometimes long time:

<img width="801" alt="Screenshot 2023-08-18 at 14 36 55" src="https://github.com/status-im/status-go/assets/1529006/7f2bf092-8d50-4273-86c7-5794169397be">
https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/activity

These are mainly `protocol` tests:

<img width="1120" alt="Screenshot 2023-08-18 at 14 38 23" src="https://github.com/status-im/status-go/assets/1529006/370de1bc-025a-4436-acda-9eda134af1d1">

Long tests runs slow down the development and makes developers experience worse.

# Implementation

Possible solutions:
- split integration tests from real unit tests if there are any
- make sure, that real unit tests are fast
- can we parallelize to utilise hardware better?

# Acceptance Criteria

I would say we should aim to 5-10 minutes total

Maybe related: #2700

**Comment by yakimant** [comment] 2023-08-18 12:50
What do you think?
@cammellos @iurimatias @richard-ramos @jakubgs

**Comment by jakubgs** [comment] 2023-08-18 13:56
I don't know much about the details of those tests, but using parallelization is probably a good idea. Either in the context of the same job or as a separate job if it makes sense to separate certain categories of tests logically.

**Comment by igor-sirotin** [comment] 2024-08-07 22:16
Duplicate of https://github.com/status-im/status-go/issues/5066

**Closed as completed by igor-sirotin** 2024-08-07 22:16 UTC
