### ISSUE TITLE
Merge balance historical data based on transfers history

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#3941] opened 2023-08-23 13:49 UTC
# Problem

Currently fetching of historical data for balance history and transfers history are two separate processes. As at the moment we fetch full (almost) transfers history after account creation, transfers history contains all data that is necessary for balance history (as well it is as precise as possible).

# Implementation
There are some requirements which led to balance history being a separate process:
- it has be ready ASAP
- we should be able to show `ALL` tab fro balance history 

In order to be able to draw some charts ASAP transfers history process should make results of history fetching for last 1/3/6 month available for usage as soon as those are fetched (instead of waiting for full scan, I did not check how this is implemented at the moment). It is also possible to adjust first few ranges so that last 1 and 3 months are scanned as fast as possible (e.g. if the first range is noticeably bigger than 1 month we should consider changing this).

As for `ALL` tab it will be covered at the moment and it should be part of a separate discussion whether it is really necessary for all accounts, even those which have hundreds or thousands transfers in history (thus are too have to be scanned fully right away).

**Comment by IvanBelyakoff** [comment] 2023-10-18 11:18
Closing it as duplicate of [this](https://github.com/status-im/status-go/issues/3835)

**Closed as completed by IvanBelyakoff** 2023-10-18 11:18 UTC
