### ISSUE TITLE
Update ethereum to solve 'nil topic' filtering bug

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#575] opened 2018-01-26 12:55 UTC
# Problem

PR is approved and we need to update our code after new Ethereum version: https://github.com/ethereum/go-ethereum/issues/15811 (already solved and merged).

# Implementation

Update Ethereum according to our process.
1. Rebase `develop` branch in [`status-im/go-ethereum`](https://github.com/status-im/go-ethereum) to `master` branch in the upstream.
2. Make sure it builds and tests pass, create a PR in [`status-im/go-ethereum`](https://github.com/status-im/go-ethereum)
3. Update `status-go`'s vendor folder (`dep ensure --update`). Make sure all tests pass, buliding is not broken. Submit a PR.

Docs
- How to update Ethereum https://www.notion.so/status/Rebasing-go-ethereum-82de0bbebe684826b62d81bc688e5e89
- How to apply Status patches https://github.com/status-im/status-go/blob/adf7895549037bea5cc287636acb2e1236c56b44/geth-patches/README.md

# Acceptance Criteria

2 PRs are merged, all tests are passed.

# Notes

May be it makes sense to rebase up to 1.8.0 Ethereum version.'
Part of https://github.com/status-im/ideas/issues/71

# Future Steps

Recheck CPU and network consumption for our basic cases.

**Comment by status-open-bounty** [comment] 2018-01-29 18:26
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8c4716091b4ad0cbfb6edf8a7c5ed614bc6e69a8be70bd1f7f54abb892a81434](https://etherscan.io/tx/0x8c4716091b4ad0cbfb6edf8a7c5ed614bc6e69a8be70bd1f7f54abb892a81434)

**Comment by divan** [comment] 2018-01-29 20:31
We're doing this by default on each geth release anyway.

**Comment by JekaMas** [comment] 2018-01-29 20:52
Next geth release is 1.8 and it can happens that rebase from 1.7.3 -> 1.8 could take much time.

**Comment by divan** [comment] 2018-01-29 20:55
Ah, so the issue is about syncing in mid-release? I'm not sure it's a good idea, how stable geth is?
Is it possible to backport your change until Geth 1.8 is available? It should be easier with patches now, and we might want this mechanism in the future.

**Comment by JekaMas** [comment] 2018-01-29 21:15
We can use patch for it however increasing the number of ethereum patches is the last thing i want. But we can try make the patch, wait until 1.8 and rebase.
If so i'll make and apply the patch and we'll rename issue as 'rebase up to 1.8'.

**Comment by divan** [comment] 2018-01-29 21:20
Nothing wrong with having temporary patches. It's definitely safer than bringing into vendor/ tree code in the middle of the development cycle that potentially can contain critical bug, just because of that fix. It also super easy to remove once Geth 1.8 is landed.

What I was trying to emphasize is that maybe it's worth to think over and discuss the whole workflow for such. Maybe special naming for temporary patches or something similar.

**Comment by JekaMas** [comment] 2018-01-30 08:00
How do you think does adding new workflow of temporaty patches increases complexity? I really agree that patch is quicker than rebase on the middle of release however it can mmake our processes more complex.
May be we need temporary patches with some naming convension, as you said, and some linter or script that checks could we remove that temporary patch?

**Comment by mandrigin** [comment] 2018-01-30 15:49
I think it makes sense to have temp patches. https://github.com/status-im/go-ethereum/pull/40 also fixes an issue on 1.7.x, but in 1.8 this bug won't be present in the current form.
So that's one more candidate on the temp patch.

**Comment by mandrigin** [comment] 2018-03-22 09:55
Closing as we don't use WhisperV5.
Feel free to reopen if you disagree.

**Closed as completed by mandrigin** 2018-03-22 09:55 UTC
