### ISSUE TITLE
Error: Missing trie node 

### ISSUE THREAD

**Issue by jaredbowie** [status-im/status-go#248] opened 2017-08-13 15:40 UTC
[missing-trie-node.zip](https://github.com/status-im/status-go/files/1220548/missing-trie-node.zip)
Receiving:
`Error: Missing trie node ` followed by a unique hash when running some functions from my contract in the status browser.  This works fine in metamask and also works fine when calling the functions from myetherwallet.  

This was happening in im.status.ethereum-fe78e7.apk and a few other nightlies that I tried.  

javascript
```javascript
var abiArray = [{"constant":false,"inputs":[{"name":"myId","type":"bytes32"},{"name":"friendId","type":"bytes32"},{"name":"debtId","type":"uint256"}],"name":"confirmDebt","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"ucac","type":"address"},{"name":"debtorId","type":"bytes32"},{"name":"creditorId","type":"bytes32"},{"name":"currencyCode","type":"bytes32"},{"name":"amount","type":"int256"},{"name":"desc","type":"bytes32"}],"name":"newDebt","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"p1","type":"bytes32"},{"name":"p2","type":"bytes32"}],"name":"confirmedDebts","outputs":[{"name":"currency2","type":"bytes32[]"},{"name":"amounts2","type":"int256[]"},{"name":"descs2","type":"bytes32[]"},{"name":"debtors2","type":"bytes32[]"},{"name":"creditors2","type":"bytes32[]"},{"name":"timestamps2","type":"uint256[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"fId","type":"bytes32"}],"name":"pendingDebts","outputs":[{"name":"debtIds","type":"uint256[]"},{"name":"confirmerIds","type":"bytes32[]"},{"name":"currency","type":"bytes32[]"},{"name":"amounts","type":"int256[]"},{"name":"descs","type":"bytes32[]"},{"name":"debtors","type":"bytes32[]"},{"name":"creditors","type":"bytes32[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_currencyCode","type":"bytes32"}],"name":"isActiveCurrency","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"s","type":"bytes32"},{"name":"l","type":"bytes32[]"}],"name":"isMember","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"myId","type":"bytes32"},{"name":"friendId","type":"bytes32"},{"name":"debtId","type":"uint256"}],"name":"rejectDebt","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"getMyFoundationId","outputs":[{"name":"foundationId","type":"bytes32"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"fId","type":"bytes32"}],"name":"pendingDebtTimestamps","outputs":[{"name":"timestamps","type":"uint256[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"fId","type":"bytes32"}],"name":"confirmedDebtBalances","outputs":[{"name":"currency","type":"bytes32[]"},{"name":"amounts","type":"int256[]"},{"name":"counterpartyIds","type":"bytes32[]"},{"name":"totalDebts","type":"uint256[]"},{"name":"mostRecent","type":"uint256[]"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_currencyCode","type":"bytes32"}],"name":"addCurrencyCode","outputs":[],"payable":false,"type":"function"},{"inputs":[{"name":"_adminId","type":"bytes32"},{"name":"dataContract","type":"address"},{"name":"friendContract","type":"address"},{"name":"foundationContract","type":"address"}],"payable":false,"type":"constructor"}]
        var MyContract = web3.eth.contract(abiArray);
        var myContractInstance = MyContract.at('0xe43950c736a5b5ed6a72513d0a349e86cc3ffdb8');
        var result = myContractInstance.pendingDebts("jared", function(error, result){
        if(!error) {
          document.getElementById("therealjb").innerHTML += " result1 " + result;
        }
        else {
            document.getElementById("therealjb").innerHTML += " error1 " + error;
          }
        });
```

Contract code here https://github.com/blockmason/credit-protocol/blob/master/contracts/FluxxxyDp.sol

Attached the full html.

**Comment by tiabc** [comment] 2017-08-13 16:01
Thanks for the detailed report, we'll look into that.

**Comment by rgeraldes** [comment] 2017-09-06 13:10
@jaredbowie is there any update on your end?

**Comment by rgeraldes** [comment] 2017-09-07 08:39
@jaredbowie the issue is related to a corrupted chaindata file and it was known as a problem in geth before but the core team has done some work on it and we've rebased our code to the latest versions of geth. In case you'd like to test with the latest version of status, you can find the build instructions here: https://wiki.status.im/contributing/development/building-status/
I'm going to close the issue for now, please let us know if you come across any issue.
Thanks for the contribution.

**Closed** 2017-09-07 08:46 UTC
Labels: bug, high-priority, intermediate
