### ISSUE TITLE
refactor(wakuv2): filter subscribe requests

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-go#4526] opened 2024-01-04 15:47 UTC
While @chaitanyaprem and I were debugging message loss when using lightclient mode, we noticed that filter subscriptions requests are being done too frequently i.e. if you have 5 content topics and a single peer, status-go executes the `FilterLightnode().Subscribe` function 5 times.  

This could be improved to reduce the number of subscribe requests sent to a peer - `FilterLightnode().Subscribe` allows for setting a content filter with up to 10 content topics and a pubsub topic.

Consider refactoring the code to first aggregate which pubsub topic x content topic subscriptions are required, and then send the FilterSubscribe request in batches of 10 content topics.

cc: @vitvly @kaichaosun, @chair28980

**Comment by vitvly** [comment] 2024-01-05 12:37
Will take it.

**Comment by chaitanyaprem** [comment] 2024-01-08 08:05
@vitvly Please consider the limit for contentFilters/contentTopics as 100. This is planned to be increased at nwaku and go-waku as well as part of https://github.com/waku-org/nwaku/issues/2338. 
Do note that Store query requests should still be limited to 10 to reduce complexity of queries generated in Store nodes.

**Comment by chaitanyaprem** [comment] 2024-06-24 05:17
Closing as this is duplicate of https://github.com/status-im/status-go/issues/5262

**Closed as completed by chaitanyaprem** 2024-06-24 05:17 UTC
Labels: waku
