### ISSUE TITLE
Unable to build bootnode due to Docker permission denied error

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#1639] opened 2019-10-12 17:31 UTC
# Problem

Unable to build bootnode.

Installed jq and docker-compose, at `4fe317917edf18404c737cb577818a3392b7300a`, using Fedora.

```
oskarth@localhost /home/oskarth/git/status-go/_assets/compose/bootnode> sudo make
Fatal: open /keys/nodekey: permission denied
Fatal: open /keys/nodekey: permission denied
make: *** [Makefile:62: keys/nodekey] Error 1

oskarth@localhost /home/oskarth/git/status-go/_assets/compose/bootnode> sudo make keys
make: 'keys' is up to date.
```

```
oskarth@localhost /home/oskarth/git/status-go/_assets/compose/bootnode> make
/usr/bin/docker-current: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See '/usr/bin/docker-current run --help'.
make: *** [Makefile:62: keys/nodekey] Error 126
```

# Acceptance Criteria

Can build bootnode in `status-go/_assets/compose/bootnode`

# Notes

After some investigation, it became clear that the bash scripts were not tested with Fedora and work only on Debian.

**Comment by oskarth** [comment] 2019-10-12 17:32
Probably something stupid

**Comment by adambabik** [comment] 2019-10-14 14:45
Why with `sudo`? I just run `make` within `_assets/compose/bootnode` and all worked fine. 

With the second snippet, it seems like some problem with your docker.

**Comment by oskarth** [comment] 2019-10-15 05:10
I'm not sure that's the issue, this is an error inside the container. The `sudo` thing is just because I didn't create a user group. If I do that with e.g. https://developer.fedoraproject.org/tools/docker/docker-installation.html I still get:

```
oskarth@localhost /home/oskarth/go/src/github.com/status-im/status-go/_assets/compose/bootnode> make
Fatal: open /keys/nodekey: permission denied
Fatal: open /keys/nodekey: permission denied
make: *** [Makefile:63: keys/nodekey] Error 1
```

Something like `docker run hello-world` works fine. Same is true if I do `docker prune` and `docker system prune` beforehand.

Are you using a completely clean slate for the container?

**Comment by adambabik** [comment] 2019-10-15 06:39
Yeah, I tried with a clean slate. Something is off with permissions of your local `$(PWD)/keys` dir and what's in the container.

Have you tried:
```
$ UID = $(shell id -u)
$ GID = $(shell id -g)
$ docker run --rm \
		-u $(UID):$(GID) \
		--entrypoint=sh \
		-v $(PWD)/keys:/keys:rw \
		ethereum/client-go:alltools-latest
```
and manually call `bootnode -genkey=/keys/nodekey`? Anything odd regarding the file permissions with `ls -al`?

**Comment by adambabik** [comment] 2019-11-25 12:50
@oskarth @jakubgs from the conversation on Status/Discord, it looks like the problem is that our bash scripts do not work well on Fedora. Any update on this issue? Should we change this issue description so that it's clear what's the root cause and how it should be fixed?

**Comment by oskarth** [comment] 2019-11-26 03:39
Oops forgot about this issue, haven't had time to try it / if I did and talked on chat later I forgot about it :sweat_smile: Right now not a priority/blocker for me personally, feel free to edit issue as you see fit. If I try again I'll report back here

**Comment by cammellos** [comment] 2020-11-03 08:37
Closing for now, feel free to re-open if still an issue

**Closed as completed by cammellos** 2020-11-03 08:37 UTC
