### ISSUE TITLE
Flaky test - TestMessengerCommunitiesTokenPermissionsSuite/TestBecomeMemberPermissions

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#4170] opened 2023-10-19 13:37 UTC
```
2023-10-19T13:26:03.152Z	DEBUG	node/node.go:185	Epoch processing	{"mvds": {"node": "04a3eebe", "epoch": 480}}
    communities_messenger_token_permissions_test.go:715: 
        	Error Trace:	/home/jenkins/workspace/status-go_prs_tests_PR-4163/protocol/communities_messenger_token_permissions_test.go:715
        	Error:      	Received unexpected error:
        	            	no messages
        	Test:       	TestMessengerCommunitiesTokenPermissionsSuite/TestBecomeMemberPermissions
```

**Comment by jrainville** [comment] 2023-10-20 21:02
I made some discoveries on this. For some reason, the sent chat message from the Owner comes in with an `UNKNOWN` message type.

```
2023-10-20T16:57:34.968-0400	DEBUG	protocol/messenger.go:3618	processing messages further	{"name": "bob", "site": "RetrieveAll", "hash": "0xea9b613fcd3cb1278389cf259d7c335e00c1c3a5536bc46a4b8ad429fc2fb06f", "count": 1}
2023-10-20T16:57:34.968-0400	INFO	protocol/messenger.go:3622	processing message	{"name": "bob", "site": "RetrieveAll", "hash": "0xea9b613fcd3cb1278389cf259d7c335e00c1c3a5536bc46a4b8ad429fc2fb06f", "message-id": "0x16313d38e05be4f4c5b4a8b802a85bdbcf2f65f8a3079b39396bfcb76793d055"}
2023-10-20T16:57:34.968-0400	INFO	protocol/messenger.go:3634	processing message	{"name": "bob", "type": "UNKNOWN", "senderID": "0x04b73103b73be19b5c9446591d046f324b2b4f4945488c9fa7f59f2de0f488bcb5fe87aa43e776f6da93f065f658be7e1ab6f1599797a1d2c8da7e89582b1bfce6"}
2023-10-20T16:57:34.968-0400	INFO	protocol/messenger_handlers.go:233	protobuf type not found	{"name": "bob", "type": "\u0000"}
2023-10-20T16:57:34.968-0400	WARN	protocol/messenger.go:3688	failed to process protobuf	{"name": "bob", "site": "RetrieveAll", "hash": "0xea9b613fcd3cb1278389cf259d7c335e00c1c3a5536bc46a4b8ad429fc2fb06f", "message-id": "0x16313d38e05be4f4c5b4a8b802a85bdbcf2f65f8a3079b39396bfcb76793d055", "error": "protobuf type not found"}
```

I haven't figured out why though. The unmarshaling should have worked correctly. I confirmed that on the sender side, the type is correctly set at `CHAT_MESSAGE`.

I'll need to dig deeper, but if anyone has an idea, please let me know. 

This issue isn't really related to this test, it's probably what is happening to most of the flaky tests, since losing the type of the message is a very generic, but also very bad issue.

**Comment by vitvly** [comment] 2023-10-24 12:31
I've also noticed that, compared to a successful run, there is an extra `Hash ratchet group id not found` error message right before the `UNKNOWN` type error:
```
2023-10-24T11:59:55.109+0300    DEBUG   common/message_sender.go:703    failed to handle an encryption message  {"name": "bob", "site": "handleMessages", "hash": "鄣\"P\ufffdv\ufffd\ufffd\u0013x\ufffdZ\ufffd\u0013\ufffd\ufffdQq\ufffdU&h벬\ufffd\ufffd\ufffd\ufffdߎ", "error": "failed to process an encrypted message: Hash ratchet group id 
not found", "errorVerbose": "Hash ratchet group id not found\nfailed to process an encrypted 
message...
```

**Comment by vitvly** [comment] 2023-10-24 12:42
Could this mean that community keys were not distributed properly here? https://github.com/status-im/status-go/blob/1be356af93cdf12c2ea10f1ee0a5a23b869af5bb/protocol/communities_messenger_token_permissions_test.go#L696

**Comment by jrainville** [comment] 2023-10-24 20:18
I tested this flaky test as well https://github.com/status-im/status-go/issues/4172 and we get the same error in the logs:
```
failed to handle an encryption message	{"site": "handleMessages", "hash": "aL\u0017K6\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0016>k\ufffd\ufffd\ufffd\ufffdh\ufffd\u0004R.\u0015\u00162\ufffd\u0004B\ufffd\ufffd\ufffd", "error": "failed to process an encrypted message: failed to unmarshal ProtocolMessage: string field contains invalid UTF-8"
```
Maybe this is the root cause of all tests?

That other test adds a role to a user, but in theory it doesn't give new keys, the message that is waited for is just the community, which should be encrypted with the community private key as far as I can tell.

I'm not sure what it all means yet. Is there a chance that we sometimes send a badly encrypted message? Could there me data corruption somewhere?

**Comment by cammellos** [comment] 2023-10-25 15:48
Looking into this, there is an issue with encryption or the mechanism indeed, so far I spotted a bug in the new code (merged yesterday) and fixed that, but the test is still flaky, investigating

**Comment by cammellos** [comment] 2023-10-25 16:04
```
USING HASH 1e8431bb9852f3e748678aa2ce7066d05b1571f473bfdb8975aaaa1870dff302
USING KEY: 816953aa8141706f682446ab1251e3b63ccd8531ecd3978d9b937f6f83ea657e
SEQ NO: 2
USING HASH 10ca3eff73ebec87d2394fc58560afeab86dac7a21f5e402ea0a55e5c8a6758f
USING KEY: 816953aa8141706f682446ab1251e3b63ccd8531ecd3978d9b937f6f83ea657e
SEQ NO: 2
```
They are using same key, same seq no, but hash is different, checking why

**Comment by jrainville** [comment] 2023-10-25 16:08
> Looking into this, there is an issue with encryption or the mechanism indeed, so far I spotted a bug in the new code (merged yesterday) and fixed that, but the test is still flaky, investigating

Thanks for looking into this. I have to say, when I tested https://github.com/status-im/status-go/issues/4172 , I was on top of develop with your fix in and it did seem more stable.

Where before I could easily reproduce with `-count 10`, now even with `-count 20` it sometimes passed. So your fix did help.

**Comment by cammellos** [comment] 2023-10-25 18:24
Thanks for the info.

Continuing the investigation:


Both devices have the same keys, correctly, but in the cache, the `Hash` is different, while any other field is the same.
Checked against the database, so it must means something goes wrong during hash generation

**Comment by cammellos** [comment] 2023-10-25 19:19
I have replicated with a low level test, this is due to out of order keys, and some database mixup, need to figure out exactly, but getting there

**Comment by cammellos** [comment] 2023-10-25 21:42
it turned out to be 2 bugs, one the one with the hash ratchet above, the second with processing encrypted messages out of order in community, I'll push a pr fixing tomorrow, but it looks like it would have been a source of a fair amount of dropped messages

**Comment by cammellos** [comment] 2023-10-25 23:32
There's yet another bug, it fails much less frequently (before it was 1/20, now it's kind of 1/100), but there's still something to look into unfortunately, I'll dig deeper tomorrow

**Comment by jrainville** [comment] 2023-10-26 14:15
Nice job @cammellos . Let me know if you want me to test or help with something

**Comment by cammellos** [comment] 2023-10-27 08:27
Still looking into this, there's definitely a bug, but can't quite pinpoint where it is yet, even with an insane amount of logs, but does seem to be related to encryption.

**Comment by cammellos** [comment] 2023-10-27 17:05
Got it finally, so it was 3 issues:
1) Introduced by my changes in the ratchet
2) Pre-existing, encrypted messages out of order were not always processed correctly
3) this looks like a major issue, if two non datasync messages were processed in the same batch, they would be dropped because of a programming mistake (wrong variable being used), this would have impacted reliability on communities messages, hard to judge the impact of it since I don't know how often messages would be processed in batches, but it would most likely happen when retrieving from mailservers (it was 100% happening when you receive a new key out of order, and that's how it was spotted in the tests, but that's also why it as flaky).

I will remove the 5000 logs stamement from my local code and send a PR on monday (tests run consistently without failing on my machine).

![download](https://github.com/status-im/status-go/assets/1017008/35239389-3bba-419b-94c8-e7123e489169)

**Comment by jrainville** [comment] 2023-10-27 17:14
Amazing job! Thank you for going through hell to figure it out. I can't wait to review it and get it merged :tada:

**Closed as completed** 2023-10-30 10:11 UTC
Labels: flaky test
