### ISSUE TITLE
review race in go-ethereum

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#176] opened 2017-05-28 14:11 UTC
![image](https://cloud.githubusercontent.com/assets/188194/26529446/89d9331a-43c8-11e7-9446-fe5585c53346.png)

**Note:** Before attempting to fix/report, we need to rebase against the latest `go-ethereum`

**Comment by tiabc** [comment] 2017-07-26 16:57
I'm fixing it as part of #205.

**Comment by tiabc** [comment] 2017-08-06 15:28
Rebase onto geth1.6.7 hasn't helped, the issue seems to be on our side or in the code we added into `go-ethereum`.

**Comment by influx6** [comment] 2017-08-17 13:50
During my tests runs am yet to see any panics beyond timeouts:

```panic: whatever you were doing takes toooo long: TestDoubleCompleteQueuedTransactions

goroutine 7789 [running]:
github.com/status-im/status-go/geth/common.PanicAfter.func1(0xc43d8445a0, 0xdf8475800, 0x49dd2c4, 0x24)
	/Users/darkvoid/devlabs/src/github.com/status-im/status-go/build/_workspace/project/src/github.com/status-im/status-go/geth/common/utils.go:95 +0x171
created by github.com/status-im/status-go/geth/common.PanicAfter
	/Users/darkvoid/devlabs/src/github.com/status-im/status-go/build/_workspace/project/src/github.com/status-im/status-go/geth/common/utils.go:97 +0x5d
exit status 2
FAIL	github.com/status-im/status-go/geth/api	304.305s
make: *** [ci] Error 1
```

**Comment by influx6** [comment] 2017-08-17 15:22
Am noticing continous failure of `TestDoubleCompleteQueuedTransactions` to finish it's run before panic `panic: whatever you were doing takes toooo long:` occurs, we need to investigate later.

**Comment by tiabc** [comment] 2017-08-27 06:53
Reproduced on the latest geth version ebf41d16a04420a3eba082cc0a1783c93caa1f86:
<img width="1205" alt="screen shot 2017-08-27 at 13 50 26" src="https://user-images.githubusercontent.com/2167748/29747762-bffedc80-8b2e-11e7-8421-d3a1571da0fd.png">

Started with `build/bin/geth --testnet console`, run for some time and typed `exit`.

**Comment by JekaMas** [comment] 2017-10-24 12:03
Here i'm going to make a list of ethereum fixes for data reces related to our project:

- [ ] https://github.com/ethereum/go-ethereum/issues/15364

**Comment by tiabc** [comment] 2017-10-28 15:12
Closing as this issue can't be reproduced any more.

@JekaMas good list but may we keep it in notion.so/status?

**Closed by tiabc** 2017-10-28 15:12 UTC
