### ISSUE TITLE
Fix nil pointer dereference somewhere in ./e2e/node

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#429] opened 2017-10-23 15:04 UTC
# Problem

Sometimes, we get panic during `./e2e/node` test.

<img width="1255" alt="screen shot 2017-10-23 at 18 01 01" src="https://user-images.githubusercontent.com/2167748/31896382-48c94cd4-b81c-11e7-8ede-f9029eca2134.png">
https://travis-ci.org/status-im/status-go/builds/291541132#L518

Setting it to high-priority as it may be something important. However, it seems to be something inside go-ethereum.

# Acceptance Criteria

10 of 10 times there's no panic while running `build/env.sh go test -timeout 5m ./e2e/node/...`

**Comment by b00ris** [comment] 2017-10-23 17:34
There is Data Race at same place. I think https://github.com/status-im/status-go/pull/412 should fix it.

**Comment by JekaMas** [comment] 2017-10-24 07:58
I think an issue is in ethereum:
```
build/_workspace/deps/src/github.com/ethereum/go-ethereum/eth/api_backend.go:178
vendor/github.com/ethereum/go-ethereum/core/tx_pool.go:442
vendor/github.com/ethereum/go-ethereum/event/subscription.go:229
```

Somewhere we do `txPool.Stop()` and then try to make new subscription, but `go-ethereum/eth/api_backend.go:178` dont check is thPool is nil.

**Comment by b00ris** [comment] 2017-10-24 08:17
I'll check it.

**Comment by b00ris** [comment] 2017-10-26 13:19
The root case is: StopNode have time to close txPool before starting EventSystem eventLoop of  StartNode.

**Comment by b00ris** [comment] 2017-11-06 08:07
Found more cases https://travis-ci.org/status-im/status-go/jobs/297000731

**Comment by b00ris** [comment] 2017-11-06 08:48
@tiabc We have to clean up data races  and add -race flag to e2e tests step by step for each package. For e2e tests with -race we could remove `TestRaceConditions` test.

**Comment by tiabc** [comment] 2017-11-07 17:47
Decreasing priority as the issue has been partly mitigated and the proper will be the possibility to run tests with the `-race` flag.

**Comment by adambabik** [comment] 2017-12-05 11:19
I believe it was fixed in #433.

**Comment by JekaMas** [comment] 2017-12-05 11:24
@adambabik I think we should reopen issue - https://travis-ci.org/status-im/status-go/jobs/311441648
As far as i can see @b00ris has decreased probability of error but doesnt remove it.

**Comment by adambabik** [comment] 2017-12-05 11:27
I see. Thanks @JekaMas, reopening.

**Comment by mandrigin** [comment] 2017-12-08 22:59
Yeah, as @b00ris mentioned the problem is here:
```go
// filter_system.go:104
func NewEventSystem(mux *event.TypeMux, backend Backend, lightMode bool) *EventSystem {
	m := &EventSystem{
		mux:       mux,
		backend:   backend,
		lightMode: lightMode,
		install:   make(chan *subscription),
		uninstall: make(chan *subscription),
	}

	go m.eventLoop()
```

and here

```go
// filter_system.go:398
// eventLoop (un)installs filters and processes mux events.
func (es *EventSystem) eventLoop() {
	var (
		index = make(filterIndex)
		sub   = es.mux.Subscribe(core.PendingLogsEvent{})
		// Subscribe TxPreEvent form txpool
		txCh  = make(chan core.TxPreEvent, txChanSize)
		txSub = es.backend.SubscribeTxPreEvent(txCh)
		// Subscribe RemovedLogsEvent
		rmLogsCh  = make(chan core.RemovedLogsEvent, rmLogsChanSize)
		rmLogsSub = es.backend.SubscribeRemovedLogsEvent(rmLogsCh)
		// Subscribe []*types.Log
		logsCh  = make(chan []*types.Log, logsChanSize)
		logsSub = es.backend.SubscribeLogsEvent(logsCh)
		// Subscribe ChainEvent
		chainEvCh  = make(chan core.ChainEvent, chainEvChanSize)
		chainEvSub = es.backend.SubscribeChainEvent(chainEvCh)
	)

	defer sub.Unsubscribe()
	defer txSub.Unsubscribe()
	defer rmLogsSub.Unsubscribe()
	defer logsSub.Unsubscribe()
	defer chainEvSub.Unsubscribe()

```

If a computer is under heavy load, it is possible that the goroutine is called after the node was already stopped. Travis CI's runners are usually like that.

To reproduce this every time, you can add `time.Sleep(1 * time.Second)` in the
beginning of the `eventLoop()` call.

One solution might be to pass a channel to the goroutine and block `NewEventSystem`
until all the subscriptions are done.
```go

go m.eventLoop(initChan)

<-initChan
```

Otherwise, we can just check unsubscriptions for `nil`, because, according to the docstrings, it is valid for `SubscribeTxPreEvent` to return nil.

**Comment by mandrigin** [comment] 2017-12-08 23:00
I'll try to prepare a PR tomorrow.

**Comment by tiabc** [comment] 2017-12-09 08:32
@mandrigin it seems you'll have to open a PR against our github.com/status-im/go-ethereum repository, not this one. Are you also going to send a PR to its upstream? It looks like a good candidate from the first glance.

**Comment by mandrigin** [comment] 2017-12-09 14:12
@tiabc In the master branch of `go-ethereum` they changed this code quite a bit, so I wasn't able to run this test at all. I don't yet know how valid is this patch against the master branch.

I made a PR against `[status-im/go-ethereum]` branch `1.7.2-stable`: [`go-ethereum/pull/38`](https://github.com/status-im/go-ethereum/pull/38/files)

That is what is used in `status-go` now, as I can see.

**Comment by santegoeds** [comment] 2017-12-10 18:37
I had a branch that was based on go-ethereum 1.7.3 and experienced the same issue there so it's definitely not fixed in the last go-ethereum release.

Fyi, @divan is working on issue #467 to upgrade to 1.7.3 with am improved approach that consists of a number of patch sets that are automatically applied.

**Comment by divan** [comment] 2017-12-11 12:07
@santegoeds yeah, I think it'll be done and merged today or tomorrow.

**Comment by mandrigin** [comment] 2017-12-11 12:37
@divan do you want me to port that fix to 1.7.3 when the rebase is done?

**Comment by divan** [comment] 2017-12-11 13:18
@mandrigin @santegoeds just to make sure we're on the same page: if the change need to be made in `go-ethereum` repo and it's not specific to Status, the process is following:
 - make a change in https://github.com/ethereum/go-ethereum
 - wait until PR is accepted
 - wait till next go-ethereum release
 - change is automatically introduced into status-go codebase as we upgrade to the new release

Does it make sense for this issue?

**Comment by mandrigin** [comment] 2017-12-11 13:52
The `master` branch of the upstream has this code rewritten, so the delay will (maybe) cause some other issues but not that particular crash. I didn't check that though, I probably should do that :)

I targeted `status-im/go-ethereum` just to get rid of that crash in the current version of the product.

**Closed** 2018-02-02 13:10 UTC

**Comment by fdouglis** [comment] 2018-02-16 23:45
I am still hitting this SEGV after rebuilding geth from the master as of today.  It's supposed to be fixed?

**Comment by mandrigin** [comment] 2018-02-17 15:58
@fdouglis are you talking about `master` or `develop` branch?

**Comment by fdouglis** [comment] 2018-02-19 16:32
@mandrigin I believe I downloaded from the master.  I can try the dev branch and see if I do better.

**Comment by mandrigin** [comment] 2018-02-19 16:34
@fdouglis `develop` is the up-to-date branch, we don't update `master` often.

**Comment by fdouglis** [comment] 2018-02-19 16:35
@mandrigin Actually: I think I am conflating go-ethereum and status-im -- you spoke here about importing a fix, and I was saying it was still broken, but I was actually referring to simple geth.  I hit this page via a search on the particular problem I encountered, which seemed to match.  But it's really go-ethereum that is at issue.  And perhaps there, I should try the dev branch rather than the master, if that's an option.

**Comment by mandrigin** [comment] 2018-02-19 16:37
@fdouglis that particular issue should be fixed in Geth 1.8. If you absolutely have to use 1.7.x, you can just apply one of our patches on the geth codebase: https://github.com/status-im/status-go/blob/develop/_assets/patches/geth/0010-geth-17-fix-npe-in-filter-system.patch

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by fdouglis** [comment] 2018-02-19 16:39
Pretty sure I'm running 1.8 and hitting that issue, or one like it.  I have details at https://github.com/ethereum/go-ethereum/issues/14552#issuecomment-366343353 if you're interested.  Maybe I'm tweaking something completely different, like a bad option somewhere, but it still shouldn't SEGV on a null reference.

**Comment by fdouglis** [comment] 2018-02-19 16:41
I probably misread your SEGV and thought it was similar, even if it is something else ... but thanks, @mandrigin
