### ISSUE TITLE
Investigate bootnodes failure to respond to a ping

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#985] opened 2018-05-22 13:25 UTC
# Problem

Observed a following log:

```
TRACE[05-22|16:20:04] <-net.timeout 
TRACE[05-22|16:20:04]                                          msg="--- (1) pongTimeout for 1b843c7697f6fc42@206.189.6.46:30404: verifyinit -> unknown (ok)"
TRACE[05-22|16:20:04] <-net.timeout 
TRACE[05-22|16:20:04]                                          msg="--- (0) pongTimeout for b29100c8468e3e66@206.189.6.48:30404: verifyinit -> unknown (ok)"
```

Basically, it means what it says that bootnode wasn't able to respond to a ping and was moved to unknown state, which can't be used for queries and as a result we can't find any peers for noticeable time.

# Implementation

Investigate why it happens
And reduce number of such errors.
I don't know how to reliably reproduce it, maybe generate significant load, it just happens sometimes.

**Comment by adriacidre** [comment] 2018-06-06 07:28
@dshulyak @pilu I'm gonna do some research on this one, any extra relevant information since its creation?

**Comment by dshulyak** [comment] 2018-06-06 08:29
@adriacidre it is hard to reproduce. it could be a temporary problem with DO cluster. so idk if it makes sense to keep it open

**Comment by gravityblast** [comment] 2018-06-06 08:33
@adriacidre  I could reproduce the `pongTimeout verifyinit -> unknown` only if the node starts without connection to another. otherwise if it goes offline later it gets a `pongTimeout contested -> unknown`.

**Comment by adriacidre** [comment] 2018-06-06 08:34
@dshulyak found a similar issue on [go-ethereum repo](https://github.com/ethereum/go-ethereum/issues/3638). 

`To connect to v5, you need to explicitly specify the discovery port number in the enode url, which will be 1 higher than the normal port number.`

but agree, we probably don't have enough info to keep research on it

**Comment by adriacidre** [comment] 2018-06-06 13:04
Closing this issue as I wasn't able to reproduce it

**Closed as completed by adriacidre** 2018-06-06 13:04 UTC
