### ISSUE TITLE
Store nodes return wrong envelopes when requesting with empty `PubsubTopic`

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#4195] opened 2023-10-24 20:20 UTC
# Problem

I have a community `0x03c892238f64e9b74cefbaaaf5d557fee401a20d6fb52da126de45755b2a2b816`
The ContentTopic for this community is `0x8c563287`.

## What we get with a valid `PubsubTopic`

If we make a this request to store nodes:
```go
MailserverBatch {
    To: time.Now(),
    From: to - 1 * Month,
    Topics: []types.Topic{ "0x8c563287" },
    PubsubTopic: "/waku/2/default-waku/proto",
}
```

We will get these envelopes:

```go
0x50ffa221d16cf1c0aa4ed690fb680800eecc4f786a9df5e9c19acb471586b160 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697709907993162000 55324
0xa1c179428825377065707cd8e315be5afbe2033f9087bd1e66c08e36fca5824a /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697709908033367000 55580
0x9cb44df191fddf61f86bcc928915fffd318b72a4807ed68915e77ceeb1d16d1d /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697710125604563000 55580
0xa27dad2fdcc7f4ad6645e0141c23bfe6c6c443a62f902290f831a80117db2afc /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697715697613760000 55580
0x779d7d38219cfb07c080d56fdb8302f3b2e661bfb4ef415096c0e678bca4f6d6 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697719499136272000 55580
0xfda750368e8573835452823dc80cc0f74a1c3c4464ac4bd9b8bc61b7495746ad /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697720384634662000 55580
0xf9549531f68206d82276ab9d52f8756ac31ca7192bb7e991ab7fc95a1852ccb5 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697720431212020000 55580
0xf5eee5e0d1b8133e4290a5f92f1bcfcbfe594e218d654b999afc9f562e4971d1 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697720437458924000 55580
0x44c3273d6d617f60283d364002dba54609e463941140c140630134fd869a45e9 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697720627695632000 55580
0x1eb7854784298ff8648e62a4a5d1ca9a713516e28107af07aac402550262dc97 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697720627708678000 55580
0x225d144a22b41140d48601e6c5fc426ab52d41e46935ba58973aece1e9921182 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697725195356356000 55580
0x2f65483b8b50b03a6d01ffd9a59922a7260b2df4f527dff374909671c464fc88 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697729227614162000 55580
0x733ec5ed9099d2c833205d1d3b16ad2ba3d3a7d9ea9b7c59ae12e4c3e4c0a175 /waku/2/default-waku/proto /waku/1/0x8c563287/rfc26 1697736596342562000 55580
```

## What we get with EMPTY `PubsubTopic`

The same batch request, but with an empty `PubsubTopic` will return this:

```go
0x22a8abb6e540ecbe1e8dc49c0843b7b4aa60dfce662d4198f6bbfce4dd40c857  /waku/1/0x8c563287/rfc26 1697709907993162000 55324
0xea81ec7078daffa5b54d520aea319b35b02d4ba4bca96c4e623f4dbf4f533370  /waku/1/0x8c563287/rfc26 1697709908033367000 55580
0x357b2b4b7ba44414d20f676a3ba0f44c5a0bd13dfabf54404997c31d19e150b0  /waku/1/0x8c563287/rfc26 1697710125604563000 55580
0xa22fa2f78fe0a4532c6a8597431293a3b558531a557fc13ca42139e40cea19c8  /waku/1/0x8c563287/rfc26 1697715697613760000 55580
0xcb986160a541dce1c745af7a31159e80aa9c39aa09fcc7e65bc534c45e6c6324  /waku/1/0x8c563287/rfc26 1697719499136272000 55580
0xd6adf45c3844ad8778c4d3e9c4550949468c4c0bd9672e8bb916f63cc11a04b8  /waku/1/0x8c563287/rfc26 1697720384634662000 55580
0x280cef09e2a1f83a5965e465a9106b12cbc18751603f498a6301c1d0407b018e  /waku/1/0x8c563287/rfc26 1697720431212020000 55580
0x1a444d8690bfb7681a517768289da6f75709e73a31dbe7e0979196dc2c761ba8  /waku/1/0x8c563287/rfc26 1697720437458924000 55580
0x0b2bb362986d4a1c608b5567f6998d7b25bcc5bbc8125d334d5f92ca28dffbd1  /waku/1/0x8c563287/rfc26 1697720627695632000 55580
0x8df93989c03500bb81e257ca38ba8c5b5160dba4c4c3445d0986c074eade2d52  /waku/1/0x8c563287/rfc26 1697720627708678000 55580
0xcf36d8289b5f1444c52c2ff1ba0f82afdbc667abb5de1b43d7bc45072c60a7fe  /waku/1/0x8c563287/rfc26 1697725195356356000 55580
0xd85c93457c0a453c0159673a30d92d96fbf149358b9105374fa5274e85df07ae  /waku/1/0x8c563287/rfc26 1697729227614162000 55580
0x142ecc3cfde2dc980c127f62d356fd23eb382cffc546fa096389757939a01231  /waku/1/0x8c563287/rfc26 1697736596342562000 55580
```

**Comment by igor-sirotin** [comment] 2024-08-30 23:11
@richard-ramos do you think I should move this ticket to `nwaku` repo?
cc @Ivansete-status

**Comment by richard-ramos** [comment] 2024-08-30 23:53
Oh. I totally missed this issue.

Is this problem still happening? The behavior i think it's okay: if you use an empty pubsub topic, then it will be ignored for the query hence you're going to get results belonging to any pubsub topic.
The problem is that status-go should not sent empty default topics. I think i i fixed this in 
- https://github.com/status-im/status-go/blob/bd0464d192971a284f29cf64c97a1914124307fe/eth-node/bridge/geth/wakuv2.go#L208
- https://github.com/status-im/status-go/blob/bd0464d192971a284f29cf64c97a1914124307fe/wakuv2/waku.go#L589

**Comment by igor-sirotin** [comment] 2024-08-31 09:35
@richard-ramos I think it shouldn't happen from status-go side anymore, yes.

What I was worried about is that the message hashes are different in this case. I assume it's because of calculating with empty `pubsubTopic`. And I think they're still the same envelopes, as the timestamps are identical.

Does it sound like an issue to me? Should we test it again?
I'm on side of just closing it, since we were basically making invalid requests. 🙂

**Comment by richard-ramos** [comment] 2024-09-01 12:32
I see. Looks like indeed the message hash seems to have been calculated bad at the time. Being done with the pubsubtopic of the request instead of using the pubsubtopic from the db row. Looking at the implementation of waku-archive in current master this shouldnt happen anymore as the message hash is now a column retrieved from the DB.

So unless @Ivansete-status says otherwise and wants to investigate more deeply, I vote for closing this issue too.

**Comment by Ivansete-status** [comment] 2024-09-06 14:19
@richard-ramos, @igor-sirotin - IIUC, having requests with different pubsubTopic values will bring different messages set. I think this can be closed

**Closed as completed** 2024-09-07 15:58 UTC
