### ISSUE TITLE
Memory Leak in statusd

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#1067] opened 2018-06-28 08:17 UTC
# Problem

There appear to be a memory leak in `statusd` that manifests itself mostly in the Digital Ocean fleet since it's more utilized.
Here's an example of hosts running out of memory:
![memory_leak](https://user-images.githubusercontent.com/2212681/42022017-68ac8936-7abc-11e8-8d8c-733cacdc1bcb.png)
https://grafana.status.im/d/YFtG6HViz/hosts-dashboard?orgId=1&from=1530101258724&to=1530173383509&var-host=node-.*&var-fleet=eth.beta&var-fleet=eth.test&var-dc=do-ams3
It happens roughly every

# Acceptance Criteria

Memory leak is identified and fixed.

# Notes

In relation to this additional metrics were exposed via geth_exporter in:
https://github.com/status-im/status-go/issues/1042

**Comment by adambabik** [comment] 2018-06-29 16:33
I cannot reproduce it on the localhost. I was connected to the cluster as a normal peer but the memory stayed the same. 

I will run tests on one of the servers.

**Comment by dshulyak** [comment] 2018-06-30 17:39
It might depend on the number of peers and received envelopes.
status-scale can be used to implement reproducible environment for this case

**Comment by jakubgs** [comment] 2018-07-02 10:52
I believe @dshulyak is right, since we didn't see hosts running out of memory on Google Cloud hosts while they were mostly unused.

**Comment by adambabik** [comment] 2018-07-05 10:46
I run a bit more tests:
1. When I run the tests on my local machine and the OS had a lot of available memory, it was steadily going up. At the same time, pprof did not report any memory leaks and used memory reported by `debug_metrics` were not increasing. This suggests that there is no memory leak but OS does not reclaim memory allocated by the process even though Go released it.
2. I did the same but in a docker container with memory limited to 50MB (`--memory=50m --memory-swap=50m`) and disabled swap. I did not receive OOM but the process reached ~48MB memory usage and stayed in that area +/- 2MB.

I checked our configuration on the servers and none of the docker containers has a memory limit set which by default allows each container to use all memory of the host. As we run a few containers, at some point host's memory runs up. 

@jakubgs As a first step, I would suggest limiting the memory allowed by each container to some sane value and make sure that all containers memory does not overflow the host's available memory.

**Comment by jakubgs** [comment] 2018-07-05 14:31
Thanks @adambabik , I've implemented some memory limits for the nodes here:
https://github.com/status-im/infra-eth-cluster/commit/72b194722be4859c97ca43326f75611c9d6658fa
Already deployed to `eth.test` and `eth.staging`. If nothing breaks I'll deploy it to `eth.beta`.

**Comment by cammellos** [comment] 2018-07-19 16:00
@adambabik just out of curiosity, I have noticed https://github.com/status-im/status-go/blob/e9c3b779b99a3debefd1b1c169c458146d8fbd70/lib/library.go#L118 
those should be created on the heap and go those not garbage collected (we should `free` them), how do they get garbage collected/memory freed? Is it possible that are a source of the memory leak?

**Comment by cammellos** [comment] 2018-07-19 16:01
I guess probably not the same, as those are mainly used by the mobile app (or only ?), but still curious :)

**Comment by adambabik** [comment] 2018-07-20 07:09
That's correct, CGo functions are only used by the mobile so that not the source of memory leaks here. 

Regarding `return C.CString(outputJSON)`, ownership transfer happens in such a case. Java or ObjC are responsible to free this memory as it can't happen in Go (it does not know for how long this memory will be needed as it merely returns it). I don't see any `CString` allocations in `library.go` which would not be returned to the caller.

**Comment by adambabik** [comment] 2018-07-20 07:11
@jakubgs how is the solution with limiting Docker containers resources doing?

**Comment by jakubgs** [comment] 2018-07-20 09:29
Pretty good. We've stopped hitting 0 free memory and 100% cpu utilization since I've added the memory limits:
![eth_beta_cpu](https://user-images.githubusercontent.com/2212681/42995044-2283cff4-8c10-11e8-9fe8-0554172e555d.png)
![eth_beta_mem](https://user-images.githubusercontent.com/2212681/42995055-2457e4f0-8c10-11e8-81a6-6b06581c8668.png)
Though it still tends towards using as much as it can until it hits the limit.

**Comment by adambabik** [comment] 2018-07-20 10:16
Thanks for the details! Yeah, it's still super strange. Clearly, there is something wrong with `statusd` executable. I have never seen such a characteristic for Go services. At the same time, the memory is fully reclaimed so it suggests some memory/GC settings rather than a memory leak.

**Comment by divan** [comment] 2018-07-20 11:25
So what's the current state – we have no ideas of the leak?

Can we deploy one server with memory profiler enabled?

**Comment by divan** [comment] 2018-07-24 22:05
So as we've seen both CPU and Memory steady growth, I assumed it must be goroutine leak (which would explain both CPU and memory increase). But after adding goroutines to metrics (#1077) and monitoring for a while, it was obvious that it's not the case - goroutines number was stable.

![screen shot 2018-07-24 at 23 00 20 2](https://user-images.githubusercontent.com/880202/43165907-6600bcb4-8f95-11e8-9599-69dfceeb5923.png)

One cluster node was deployed with profiling enabled (thanks @jakubgs) and I restarted node, saved heap profile from server, then waited a few hours and collected again, so it could be used with `-base` option of `pprof`:

```
go tool pprof -alloc_objects -base heap1.pprof heap2.pprof
```
I haven't found any big objects or huge number of allocations, so I started saving heap profiles in debug mode (`http://.../debug/pprof/heap?debug1` URL). After having a few debug outputs, I ran small script to do diff comparison of the changed entries over time, and then started manually inspecting stacktraces.

One particular stacktrace catched my eye, as I believed the underlying function should be running at all in a first place:
```
0: 0 [13: 34944] @ 0x4fe14d 0x4fdb01 0x4fdee9 0x517fc2 0x515de6 0x520a04 0x517223 0x520c04 0x516fdc 0x520b84 0x516d01 0x520b04 0x513cc2 0x515b2b 0x515e65 0x520a04 0x517223 0x520c04 0x517223 0x520c04 0x513cc2 0x5139b5 0x5133bf 0xb905e0 0xb8fa5a 0xd0662d 0xd05ae8 0xd094ce 0x46ef51
#   0x4fe14c    bytes.makeSlice+0x6c                                /usr/local/go/src/bytes/buffer.go:230
#   0x4fdb00    bytes.(*Buffer).grow+0x150                          /usr/local/go/src/bytes/buffer.go:144
#   0x4fdee8    bytes.(*Buffer).WriteString+0xd8                        /usr/local/go/src/bytes/buffer.go:186
#   0x517fc1    encoding/json.(*encodeState).string+0x481                   /usr/local/go/src/encoding/json/encode.go:945
#   0x515de5    encoding/json.(*structEncoder).encode+0x1d5                 /usr/local/go/src/encoding/json/encode.go:636
#   0x520a03    encoding/json.(*structEncoder).(encoding/json.encode)-fm+0x63           /usr/local/go/src/encoding/json/encode.go:653
#   0x517222    encoding/json.(*ptrEncoder).encode+0xe2                     /usr/local/go/src/encoding/json/encode.go:780
#   0x520c03    encoding/json.(*ptrEncoder).(encoding/json.encode)-fm+0x63          /usr/local/go/src/encoding/json/encode.go:785
#   0x516fdb    encoding/json.(*arrayEncoder).encode+0xdb                   /usr/local/go/src/encoding/json/encode.go:761
#   0x520b83    encoding/json.(*arrayEncoder).(encoding/json.encode)-fm+0x63            /usr/local/go/src/encoding/json/encode.go:768
#   0x516d00    encoding/json.(*sliceEncoder).encode+0xc0                   /usr/local/go/src/encoding/json/encode.go:735
#   0x520b03    encoding/json.(*sliceEncoder).(encoding/json.encode)-fm+0x63            /usr/local/go/src/encoding/json/encode.go:747
#   0x513cc1    encoding/json.(*encodeState).reflectValue+0x81                  /usr/local/go/src/encoding/json/encode.go:325
#   0x515b2a    encoding/json.interfaceEncoder+0xda                     /usr/local/go/src/encoding/json/encode.go:611
#   0x515e64    encoding/json.(*structEncoder).encode+0x254                 /usr/local/go/src/encoding/json/encode.go:639
#   0x520a03    encoding/json.(*structEncoder).(encoding/json.encode)-fm+0x63           /usr/local/go/src/encoding/json/encode.go:653
#   0x517222    encoding/json.(*ptrEncoder).encode+0xe2                     /usr/local/go/src/encoding/json/encode.go:780
#   0x520c03    encoding/json.(*ptrEncoder).(encoding/json.encode)-fm+0x63          /usr/local/go/src/encoding/json/encode.go:785
#   0x517222    encoding/json.(*ptrEncoder).encode+0xe2                     /usr/local/go/src/encoding/json/encode.go:780
#   0x520c03    encoding/json.(*ptrEncoder).(encoding/json.encode)-fm+0x63          /usr/local/go/src/encoding/json/encode.go:785
#   0x513cc1    encoding/json.(*encodeState).reflectValue+0x81                  /usr/local/go/src/encoding/json/encode.go:325
#   0x5139b4    encoding/json.(*encodeState).marshal+0xa4                   /usr/local/go/src/encoding/json/encode.go:298
#   0x5133be    encoding/json.Marshal+0x5e                          /usr/local/go/src/encoding/json/encode.go:161
#   0xb905df    github.com/status-im/status-go/signal.send+0xcf                 /go/src/github.com/status-im/status-go/signal/signals.go:40
#   0xb8fa59    github.com/status-im/status-go/signal.SendDiscoverySummary+0x49         /go/src/github.com/status-im/status-go/signal/events_discovery.go:26
#   0xd0662c    github.com/status-im/status-go/peers.SendDiscoverySummary+0x6c          /go/src/github.com/status-im/status-go/peers/signal.go:10
#   0xd05ae7    github.com/status-im/status-go/peers.(*PeerPool).handleServerPeers+0x387    /go/src/github.com/status-im/status-go/peers/peerpool.go:250
#   0xd094cd    github.com/status-im/status-go/peers.(*PeerPool).Start.func1+0x3d       /go/src/github.com/status-im/status-go/peers/peerpool.go:130
```

First of all, `SendDiscoverySummary` doesn't make sense for server code. We use signals to notify UI code, nothing else. Second, there are 58 more heap profiler stacktraces originating with `SendDiscoverySummary`, which is definitely suscpicios, and one of them in particular:

```
0: 0 [22: 107008] @ 0x45a927 0xb902bb 0xb90927 0xb903eb 0x46c78b 0x41632c 0x4160fa 0x46dd5b 0x46dbf2 0x415fa8 0xb90326 0xb90717 0xb8fa5a 0xd0662d 0xd05ae8 0xd094ce 0x46ef51
#   0xb902ba    github.com/status-im/status-go/signal._Cfunc_GoString+0x2a          _cgo_gotypes.go:51
#   0xb90926    github.com/status-im/status-go/signal.NotifyNode+0x66               /go/src/github.com/status-im/status-go/signal/signals.go:80
#   0xb903ea    github.com/status-im/status-go/signal._cgoexpwrap_4354e057a1a7_NotifyNode+0x2a  _cgo_gotypes.go:90
#   0x46c78a    runtime.call32+0x3a                             /usr/local/go/src/runtime/asm_amd64.s:573
#   0x41632b    runtime.cgocallbackg1+0x19b                         /usr/local/go/src/runtime/cgocall.go:316
#   0x4160f9    runtime.cgocallbackg+0xd9                           /usr/local/go/src/runtime/cgocall.go:194
#   0x46dd5a    runtime.cgocallback_gofunc+0x9a                         /usr/local/go/src/runtime/asm_amd64.s:826
#   0x46dbf1    runtime.asmcgocall+0x41                             /usr/local/go/src/runtime/asm_amd64.s:673
#   0x415fa7    runtime.cgocall+0x87                                /usr/local/go/src/runtime/cgocall.go:131
#   0xb90325    github.com/status-im/status-go/signal._Cfunc_StatusServiceSignalEvent+0x45  _cgo_gotypes.go:73
#   0xb90716    github.com/status-im/status-go/signal.send+0x206                /go/src/github.com/status-im/status-go/signal/signals.go:44
#   0xb8fa59    github.com/status-im/status-go/signal.SendDiscoverySummary+0x49         /go/src/github.com/status-im/status-go/signal/events_discovery.go:26
#   0xd0662c    github.com/status-im/status-go/peers.SendDiscoverySummary+0x6c          /go/src/github.com/status-im/status-go/peers/signal.go:10
#   0xd05ae7    github.com/status-im/status-go/peers.(*PeerPool).handleServerPeers+0x387    /go/src/github.com/status-im/status-go/peers/peerpool.go:250
#   0xd094cd    github.com/status-im/status-go/peers.(*PeerPool).Start.func1+0x3d       /go/src/github.com/status-im/status-go/peers/peerpool.go:130
```

I checked this function, and guess what - we never free memory, allocated by`C.CString()` function! Which, in this case, contains full JSON dump of peers info, and easily could be tens of KBs in size:

```go
// send sends application signal (in JSON) upwards to application (via default notification handler)
func send(typ string, event interface{}) {
	signal := NewEnvelope(typ, event)
	data, err := json.Marshal(&signal)
	if err != nil {
		logger.Error("Marshalling signal envelope", "error", err)
	}
	C.StatusServiceSignalEvent(C.CString(string(data)))
}
```

That seems to be a Cgo usage inherited from the early days of codebase – none of `C.CString` usage in `lib/` for example, doesn't free memory. But that should be addressed and fixed in a separate PR I believe.

For now I propose to free memory in this function and see if it'll have any impact. My main doubts are related to CPU usage numbers – GC unlikely to increase CPU usage so much. I suspect there is some bug with signal code. Anyway, opened PR: https://github.com/status-im/status-go/pull/1114 for that.

Also, I guess there is no sense to compile `signal` package at all for server code – that should be done via build tags, and compiled only in a lib mode.

**Comment by jakubgs** [comment] 2018-07-24 23:33
This is some amazing work @divan, thanks a lot for all of your research and for documenting your findings in such a detailed way.
Maybe a writeup of how you did your research or a short presentation could let others learn how to debug such issues. It would be pretty amazing!

**Comment by adambabik** [comment] 2018-07-25 07:10
Great stuff! I did a similar thing but I did not follow up with `so I started saving heap profiles in debug mode`. I forgot that CGO stuff is not well handled by some `go tool`s. 

Overall, an interesting case that proves again that using CGO should be avoided.

**Comment by divan** [comment] 2018-07-25 13:13
@adambabik thanks, yeah, CGo is (not)surprisingly bad thing to debug with profiles.
@jakubgs thanks, but I think this topic is well covered in talks and articles – I know from memory a few really awesome talks on Go profiling from Brad Fitzpatrick and Prashant Varanasi.

**Closed as completed** 2018-07-26 11:04 UTC
