### ISSUE TITLE
Add Start and Stop Methods to Jail

### ISSUE THREAD

**Issue by influx6** [status-im/status-go#379] opened 2017-09-29 15:27 UTC
# Problem

We are have jail cells which are forever alive and never disposed of during the life cycle of the status react app, which leads to specific issues like endless goroutines for the cells `loop` which handles task execution on the event loop for jail. This pose a problem and with @divan addition of cancelation of a cell's loop in #376, that leviates things abit, but does not total solve the issue, where if the `Stop` method is called, then a jail `Cell` instance becomes unsable.

# Implementation
To resolve this issue, and allow react side to be able to start and stop user account related Jail `Cells`, we need to do the following:

- Add `Start` method to all jail `Cell` to the already existing `Stop` method, which allows each `Cell.loop` instance to be stopped and started (instantiated/re-instantiated) as needed.
- Expose `StartCell(chatId)` and `StopCell(chatId)` methods to react, to allow starting and stopping a `Cell` loop, either when the user switches account or does something that removes focus from the chat window of the respective account user.

Known steps towards feature implementation.
What needs further specifying and investigating.

# Acceptance Criteria

- Able to start and stop jail `Cell` without side effect of panic or task blow up
- Task pending must either be cached or totally removed (I go for remove) when cell is stopped. (I believe PR for #376 already achieves this).

# Future Steps

- Inform `ClojureTeam` about new methods and have them utilized with account switching initially.

**Comment by tiabc** [comment] 2017-10-09 17:46
Closing as a duplicate of #260 with fixes in #376 and #382 (which doesn't expose jail cells to status-react but handles it internally upon `SwitchAccount` and `Logout` which is more correct). 
Feel free to re-open if you think this issue is still needed.

**Closed by tiabc** 2017-10-09 17:46 UTC
Labels: enhancement, medium-priority
